title: "Lee Yih Ven's Data Analyst Portfolio"
description: "My professional portfolio showcasing case studies and data analysis projects."
baseurl: "/data-analyst-portfolio"
url: "https://lyven81.github.io"
theme: minima

collections:
  case-studies:
    output: true
